
# specifying-parser
parser: babel-eslint

# specifying-environments
env:
  browser: true
  node: true

# configuring-plugins
plugins:
  - import

# configuring-rules
rules:
  # possible errors
  no-console:
    - off
  # variables
  no-unused-vars:
    - off
  # stylistic issues
  comma-dangle:
    - error
    - always-multiline
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  new-parens:
    - error
  no-mixed-spaces-and-tabs:
    - error
  quotes:
    - error
    - single
  semi:
    - error
    - never

# extending-configuration-files
extends:
  - eslint:recommended

# configuration-cascading-and-hierarchy
root: true
