
# configuration-cascading-and-hierarchy
  root: true

# extending-configuration-files
  extends:
    # eslint:recommended
    - plugin:@typescript-eslint/eslint-recommended
    - plugin:@typescript-eslint/recommended
    # plugin:@typescript-eslint/recommended-requiring-type-checking

## specifying-environments
#  env:
#    browser: true
#    node: true
#    es6: true
#    jest: true

## configuring-plugins
#  plugins:
#    - import
#    - react
#    - jest

# configuring-rules
  rules:
    # possible errors
      '@typescript-eslint/no-console':
        - off
    # variables
      '@typescript-eslint/no-unused-vars':
        - off
    # stylistic issues
      '@typescript-eslint/comma-dangle':
        - error
        - always-multiline
      '@typescript-eslint/indent':
        - error
        - tab
        - SwitchCase: 1
      '@typescript-eslint/linebreak-style':
        - error
        - unix
      '@typescript-eslint/new-parens':
        - error
      '@typescript-eslint/no-mixed-spaces-and-tabs':
        - error
      '@typescript-eslint/quotes':
        - error
        - single
      '@typescript-eslint/semi':
        - error
        - never
