
# rules
  rules:
    # possible errors
      # property
        property-no-unknown:
          - true
          - ignoreProperties:
            - border-bottom-radius
            - border-top-radius
    # limit language features
      # color
        color-named: null
    # stylistic issues
      # general
        indentation: tab

# extends
  extends:
    - stylelint-config-sugarss-recommended
