
extends: stylelint-config-standard

rules:
  
  # property
  property-no-unknown:
    - true
    - ignoreProperties:
      - border-bottom-radius
      - border-top-radius
  
  # at-rule
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
      - define-mixin
      - mixin
  
  # declaration
  declaration-empty-line-before: never
  
  # declaration block
  declaration-block-trailing-semicolon: never
  
  # block
  block-closing-brace-newline-before: null
  block-opening-brace-space-before: null
  
  # at-rule
  at-rule-empty-line-before: null
  
  # general
  indentation: tab
